### ISSUE TITLE
[FEATURE REQUEST] Add "Generate Getter/Setter" as a quick command

### ISSUE THREAD

**Issue by RenanLazarotto** [cvergne/vscode-php-getters-setters#7]
Hey!
Is in the plans to add the option to generate getters and setters as a command invoked by Command Palette? Right now, having to reach the mouse to do so kinda breaks my workflow.
It would be nice if I could select the properties without getter/setter and generate all of them at once rather than manually selecting one by one and generating it using the context menu

**Comment by cvergne** [comment]
Hi, my initial plan was first of all to make the extension working again with vscode, so no specific roadmap on the plugin for now, but it's a good idea :)
However I think it's not an quick and easy feature to do because it means all the file needs to be parsed I guess.
Don't hesitate to make a PR (even a start of work as a draft PR) if you can ;)

**Comment by cvergne** [comment]
@NoxLP has made a wonderful job with PR #13 by adding a new command to generate all getters/setters of the file at once, and it's available from the command palette (and other commands are too) :)
